version: '3.9'

services:
  rstudio:
    ports:
      - 8787:8787
    container_name: rstudio_server
    volumes:
      - ./packages/:/packages
      - /path/to/data/rstudio/:/home/rstudio/work # One for each user
    environment:
      - PASSWORD=password # Change it!!
      - USERID=1001
      - GROUPID=1001
    image: davetang/rstudio:4.2.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rstudio.rule=Host(`your.domain.es`)"
      - "traefik.http.routers.rstudio.entrypoints=websecure"
      - "traefik.http.routers.rstudio.tls.certresolver=letsencrypt"
      - "traefik.http.services.rstudio.loadbalancer.server.port=8787"
      - "traefik.http.routers.calibre.middlewares=authelia" # Enables SSO with Authelia

  traefik:
    image: traefik:2.9.6
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/logs:/logs
      - ./config/traefik/acme.json:/acme.json
      - ./config/traefik/credentials:/credentials:ro
      - ./config/letsencrypt:/letsencrypt
    command:
      # API Dashboard
      - "--api.dashboard=true"
      # Docker discovery
      - "--providers.docker=true"
      - "--providers.docker.network=$DEFAULT_NETWORK"
      - "--providers.docker.exposedByDefault=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.internal.address=:8080"
      # HTTPS redirection
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
#      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
#      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns"
      # Logging settings
      - "--log=true"
      - "--log.level=WARN"
      - "--accessLog=true"
      - "--accessLog.filePath=logs/traefik.log"
      - "--accessLog.bufferingSize=100"
      # Ping
      - "--ping=true"
      - "--ping.entryPoint=internal"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.enable=false"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`$DOMAIN_NAME`)"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      # --- Middlewares ---
      # Basic auth
      - "traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/credentials/traefik"
      # Security Headers: HTTP Strict Transport Security (HSTS)
      - "traefik.http.middlewares.security-headers.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stsPreload=true"
      # Security Headers: X-Frame-Options
      - "traefik.http.middlewares.security-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      # Security Headers: X-Content-Type-Options
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      # Security Headers: X-XSS-Protection
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      # Security Headers: Referrer-Policy
      - "traefik.http.middlewares.security-headers.headers.referrerPolicy=same-origin"
      # Security Headers: Permissions-Policy
      - "traefik.http.middlewares.security-headers.headers.permissionsPolicy=camera=(),microphone=(),usb=()"

    extra_hosts:
      - host.docker.internal:172.17.0.1 # https://doc.traefik.io/traefik/providers/docker/#host-networking

  authelia:
    image: authelia/authelia:4.36.9
    container_name: authelia
    hostname: authelia
    restart: unless-stopped
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/config/secrets/jwt
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/secrets/encryption_key
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - ./config/configuration.yml:/config/configuration.yml
      - ./config/users.yml:/config/users.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.rule=Host(`authelia.your.domain.org`)"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
      # --- Authelia Middleware ---
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.your.domain.org/"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"

networks:
  default:
    external: true
    name: traefik
